events/urls.py
from django.urls import path
from . import views

app_name = 'events'
urlpatterns = [
    path('', views.events, name='events'),
    path('register/', views.register, name='register'),
    path('register/member/<str:event_site>/', views.member_regist_event, name='member_register'),
    path('register/google-member/<str:event_site>/', views.google_member_regist_event, name='google_member_register'),
    path('register/non-member/<str:event_site>/', views.non_member_regist_event, name='non_member_register'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.loginpage, name='loginpage'),
]

student_union/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views
from django.conf import settings

urlpatterns = [
    path('', include('main.urls')),
	path('', include('about.urls')),
    path('events/', include('events.urls')),
    path('news/', include('news.urls')),
    path('member/', include('member.urls')),
    path('userpage/',include('userinfo.urls')),
    path('admin/', admin.site.urls),
    path('login/', views.LoginView.as_view(template_name="useraccounts/login.html"), name='login'),
    path('logout/', views.LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path('auth/', include('social_django.urls', namespace='social')),  # <- Here

]

events/models.py
import datetime
from django.db import models
from django.utils import timezone
from member.models import Member
from django.contrib.auth.models import User

class NonMemberParticipant(models.Model):
    username = models.CharField(max_length=15, unique=True)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=15)

    class Meta:
        verbose_name_plural = 'non member participants'

    def __str__(self):
        return self.username

class Event(models.Model):
    site = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    image_url = models.CharField(max_length=300)
    details = models.TextField()
    date = models.DateTimeField()
    member_participants = models.ManyToManyField(Member, blank=True)
    google_member_participants = models.ManyToManyField(User, blank=True)
    non_member_participants = models.ManyToManyField(NonMemberParticipant, blank=True)

    class Meta:
        verbose_name_plural = 'events'

    def __str__(self):
        return self.name

events/forms.py
from django.core.validators import RegexValidator
from django import forms
from .models import Event, NonMemberParticipant

class MemberRegistEventForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'required': True,
    }))
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'required': True,
    }))
    
    class Meta:
        model = Event
        fields = ('username', 'password')

class NonMemberRegistEventForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'required': True,
    }), max_length=15)
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'required': True,
    }), min_length=8,
        validators=[RegexValidator('^(\w+\d+|\d+\w+)+$',
        message="Password should be a combination of Alphabets and Numbers")])

    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'required': True,
    }), label='E-mail')
    
    class Meta:
        model = Event
        fields = ('username', 'password', 'email')

events/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from member.models import Member
from social_django.models import *
from django.views.decorators.csrf import csrf_exempt
from .models import Event, NonMemberParticipant
from .forms import MemberRegistEventForm, NonMemberRegistEventForm

def events(request):
	all_events = Event.objects.all()
	return render(request, 'events/events.html', {'all_events': all_events})

def register(request):
    return render(request, 'events/register.html', {})

def google_member_regist_event(request, event_site):
    event = get_object_or_404(Event, site=event_site)
    if (request.user.is_authenticated):
        if (request.method == 'POST'):
            event.google_member_participants.add(User.objects.filter(username=request.user.username)[0])
            event.save()
            return render(request, 'events/google_member_register.html', {'event': event, 'message': 'Registered!'})
        else:
            return render(request, 'events/google_member_register.html', {'event': event})
    else:
        return HttpResponseRedirect('/login/')

def member_regist_event(request, event_site):
    event = get_object_or_404(Event, site=event_site)
    if (request.method == 'POST'):
        regist_event_form = MemberRegistEventForm(request.POST)
        if (regist_event_form.is_valid()):
            for member in Member.objects.all():
                if member.username == request.POST['username'] and member.password == request.POST['password']:
                    event.member_participants.add(member)
                    event.save()
                    return render(request, 'events/member_register.html', {'event': event, 'regist_event_form': regist_event_form, 'message': 'Registered!'})
        return render(request, 'events/member_register.html', {'event': event, 'regist_event_form': regist_event_form, 'message': 'Wrong username or password'})
    else:
        regist_event_form = MemberRegistEventForm()
    return render(request, 'events/member_register.html', {'event': event, 'regist_event_form': regist_event_form})

def non_member_regist_event(request, event_site):
    event = get_object_or_404(Event, site=event_site)
    if (request.method == 'POST'):
        regist_event_form = NonMemberRegistEventForm(request.POST)
        if (regist_event_form.is_valid()):
            data = NonMemberParticipant(
                username = request.POST['username'],
                email = request.POST['email'],
                password = request.POST['password'],
                )
            data.save()

            event.non_member_participants.add(data)
            event.save()
            return render(request, 'events/non_member_register.html', {'event': event, 'regist_event_form': regist_event_form, 'message': 'Registered!'})
    else:
        regist_event_form = NonMemberRegistEventForm()
    return render(request, 'events/non_member_register.html', {'event': event, 'regist_event_form': regist_event_form})

events/templates/events/events.html
{% extends "main/base.html" %}
{% load staticfiles %}

{% block title %}Events{% endblock %}

{% block content %}
<div class="container" style="padding: 3%;">
    <div class="text-center">
        <div class="card-deck">
            {% for event in all_events %}
            <div class="card">
                <img class="card-img-top" src="{{ event.image_url }}" alt="Card image cap">
                <div class="card-body">
                    <h3 class="card-title">{{ event.name }}</h3>
                    <h6>{{ event.date }}</h6>
                    <p class="card-text">
                        {{ event.details }}
                    </p>
                    <a class="btn btn-outline-dark" href="{% url 'events:member_register' event_site=event.site %}">Member Registration</a>
                    <div style="margin-bottom: 10px;"></div>
                    <a class="btn btn-outline-dark" href="{% url 'events:google_member_register' event_site=event.site %}">Google Member Registration</a>
                    <div style="margin-bottom: 10px;"></div>
                    <a class="btn btn-outline-dark" href="{% url 'events:non_member_register' event_site=event.site %}">Non Member Registration</a>

                    <hr />
                    <h6>Member participants:</h6>
                    {% if event.member_participants.all %}
                    {% for member_participant in event.member_participants.all %}
                    <p style="margin-bottom: 1px">{{ member_participant.username }}</p>
                    {% endfor %}
                    {% else %}
                    <p style="margin-bottom: 1px">None</p>
                    {% endif %}

                    <hr />
                    <h6>Google Member participants:</h6>
                    {% if event.google_member_participants.all %}
                    {% for google_member_participant in event.google_member_participants.all %}
                    <p style="margin-bottom: 1px">{{ google_member_participant.username }}</p>
                    {% endfor %}
                    {% else %}
                    <p style="margin-bottom: 1px">None</p>
                    {% endif %}

                    <hr />
                    <h6>Non Member participants:</h6>
                    {% if event.non_member_participants.all %}
                    {% for non_member_participant in event.non_member_participants.all %}
                    <p style="margin-bottom: 1px">{{ non_member_participant.username }}</p>
                    {% endfor %}
                    {% else %}
                    <p style="margin-bottom: 1px">None</p>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

events/templates/events/google_member_register.html
{% extends "main/base.html" %}
{% load staticfiles %}

{% block title %}{{ event.name }} Registration{% endblock %}

{% block content %}
{% if user.is_authenticated %}
	<div class="container">
		<div class="row" style="padding-top:3%">
			<div class="col-6">
                {% if message %}
                <h4>{{ message }}</h4>
                {% endif %}
                <h3 style="color: rgb(255, 194, 80)">Hi, {{ user.first_name }}! Please click the button below to register to {{ event.name }} event!</h3>
				<form action="{% url 'events:google_member_register' event_site=event.site %}" method="POST">
					{% csrf_token %}
					<br>
					<button class="btn btn-outline-dark btn-lg" type="submit" value="Create participant">REGIST</button>
				</form>
			</div>
			
			<div class="col-6">
				<center><h1 class = "sub-title-ev"><strong><i>R E G I S T<br> N O W !</i></strong></h1></center>
			</div>
			
		</div>
    </div>
	{% include 'events/img_down.html' %}
             
{% else %}
	<script type="text/javascript">
    	alert("Please Login First")
    	window.location.replace("{% url 'events:events' %}")
    </script>
{% endif %}
    
	
{% endblock content %}

events/templates/events/img_down.html
{% load staticfiles %}

{% block content %}
<head>
	<meta charset = "utf-8" name = "viewport" content = "width = device-width, initial-scale = 1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'events/css/css_reg_event.css' %}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
	
<div class="row" id="box-search">
    <div class="thumbnail text-center">
        <img src="{% static 'events/img/yellowcity.jpg' %}" alt="image-on-top-of-footer" class="img-fluid">
    </div>
</div>
{% endblock content %}

events/templates/events/member_register.html
{% extends "main/base.html" %}
{% load staticfiles %}

{% block title %}{{ event.name }} Registration{% endblock %}

{% block content %}

	<div class="container">
		<div class="row" style="padding-top:3%">
			<div class="col-6">
                <h3 style="color: rgb(255, 194, 80)"> {{ event.name }} event registration form for Student Union Member</h3>
                {% if message %}
                <h4>{{ message }}</h4>
                {% endif %}
				<form action="{% url 'events:member_register' event_site=event.site %}" method="POST">
					{% csrf_token %}
					{{ regist_event_form }}
					<br>
					<button class="btn btn-outline-dark btn-lg" type="submit" value="Create participant">REGIST</button>
				</form>
			</div>
			
			<div class="col-6">
				<center><h1 class = "sub-title-ev"><strong><i>R E G I S T<br> N O W !</i></strong></h1></center>
			</div>
			
		</div>
    </div>
	{% include 'events/img_down.html' %}
             

    
	
{% endblock content %}

events/templates/events/non_member_register.html
{% extends "main/base.html" %}
{% load staticfiles %}

{% block title %}{{ event.name }} Registration{% endblock %}

{% block content %}

	<div class="container">
		<div class="row" style="padding-top:3%">
			<div class="col-6">
                <h3 style="color: rgb(255, 194, 80)"> {{ event.name }} event registration form for Non Student Union Member</h3>
                {% if message %}
                <h4>{{ message }}</h4>
                {% endif %}
				<form action="{% url 'events:non_member_register' event_site=event.site %}" method="POST">
					{% csrf_token %}
					{{ regist_event_form }}
					<br>
					<button class="btn btn-outline-dark btn-lg" type="submit" value="Create participant">REGIST</button>
				</form>
			</div>
			
			<div class="col-6">
				<center><h1 class = "sub-title-ev"><strong><i>R E G I S T<br> N O W !</i></strong></h1></center>
			</div>
			
		</div>
    </div>
	{% include 'events/img_down.html' %}
            
	
{% endblock content %}

events/templates/events/register.html
{% extends "main/base.html" %}
{% load staticfiles %}

{% block title %}{{ event.name }} Registration{% endblock %}

{% block content %}
    <div class="container">
		<div class="row" style="padding-top:3%">
            <center><h1 class = "sub-title-ev"><strong><i>Please select the event that you want in the events page first!</i></strong></h1></center>
		</div>
    </div>
	{% include 'events/img_down.html' %}
	
{% endblock content %}