main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.loginpage, name='loginpage'),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('', views.news, name='news'),
    path('<str:news_site>/', views.detail, name='detail'),
]

student_union/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views
from django.conf import settings

urlpatterns = [
    path('', include('main.urls')),
	path('', include('about.urls')),
    path('events/', include('events.urls')),
    path('news/', include('news.urls')),
    path('member/', include('member.urls')),
    path('userpage/',include('userinfo.urls')),
    path('admin/', admin.site.urls),
    path('login/', views.LoginView.as_view(template_name="useraccounts/login.html"), name='login'),
    path('logout/', views.LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path('auth/', include('social_django.urls', namespace='social')),  # <- Here

]

news/models.py
import datetime
from django.db import models
from django.utils import timezone
from member.models import Member

class News(models.Model):
    site = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    image_url = models.CharField(max_length=300)
    details = models.TextField()
    pub_date = models.DateTimeField('date published')
    likers = models.ManyToManyField(Member, blank=True)

    class Meta:
        verbose_name_plural = "news"

    def __str__(self):
        return self.title

news/forms.py
from django.core.validators import RegexValidator
from django import forms
from member.models import Member
from .models import News

class LikeForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'required': True,
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'required': True,
    }))

    class Meta:
        model = News
        fields = ('username', 'password')

news/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
from django.template import RequestContext, loader
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse
from member.models import Member
from .models import News
from .forms import LikeForm

def news(request):
	all_news = News.objects.all()
	return render(request, 'news/news.html', {'all_news': all_news})

def detail(request, news_site):
    news = get_object_or_404(News, site=news_site)
    if (request.method == 'POST'):
        like_form = LikeForm(request.POST)
        if (like_form.is_valid()):
            for member in Member.objects.all():
                if member.username == request.POST['username'] and member.password == request.POST['password']:
                    news.likers.add(member)
                    news.save()
                    return render(request, 'news/detail.html', {'news': news, 'likers': news.likers.all(), 'like_form': like_form, 'message': 'Like added!'})
        return render(request, 'news/detail.html', {'news': news, 'likers': news.likers.all(), 'like_form': like_form, 'message': 'Wrong username or password'})
    else:
        like_form = LikeForm()
    return render(request, 'news/detail.html', {'news': news, 'likers': news.likers.all(), 'like_form': like_form})

news/templates/news/detail.html
{% extends "main/base.html" %}
{% load staticfiles %}

{% block title %}{{ news.title }}{% endblock %}

{% block content %}
<head>
    <style>
        #like-form {
            display: none;
        }
    </style>
</head>

<div class="container"  style=" display: flex;justify-content: center; padding: 3%;">
    <div class="text-center">
        <div class="card" style="width: 50vw;">
            <img class="card-img-top" src="{{ news.image_url }}" alt="Card image cap">
            <div class="card-body">
                <button type="button" class="btn btn-link" onclick="toogle()"><img src="{% static 'news/img/like.jpg' %}" alt="HTML tutorial" style="width:42px;height:42px;border:0;"></button>
                
                <div id="like-form">
                    <form class="status-form" action="{% url 'news:detail' news_site=news.site %}" method="POST">
                        {% csrf_token %}
                        {{ like_form }}
                        <br />
                        <button class="btn btn-outline-dark btn-lg" type="submit" value="Like">Like!</button>
                    </form>
                    <hr />
                </div>

                {% if message %}
                <h4>{{ message }}</h4>
                {% endif %}

                <h3><Strong>{{ news.title }}</Strong></h3>
                <h6>{{ news.pub_date }}</h6>
                <p class="card-text">
                    {{ news.details|linebreaks }}
                </p>
                
                <br />
                <h6>Liked by:</h6>
                {% if likers %}
                {% for liker in likers %}
                <p style="margin-bottom: 1px">{{ liker.username }}</p>
                {% endfor %}
                {% else %}
                <p style="margin-bottom: 1px">None</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<script>
    function toogle() {
        var x = document.getElementById("like-form");
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    }
</script>    
{% endblock %}

news/templates/news/news.html
{% extends "main/base.html" %}
{% load staticfiles %}

{% block title %}News{% endblock %}

{% block content %}
<div id="carousel" class="carousel slide" data-ride="carousel">
	<ol class="carousel-indicators">
		{% for news in all_news %}
        <li data-target="#carousel" data-slide-to="{{ forloop.counter0 }}" class="{% if forloop.counter0 == 0 %}active{% endif %}"></li>
		{% endfor %}
	</ol>
	<div class="carousel-inner">
		{% for news in all_news %}
		<div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}">
			<img class="d-block w-100" src="{{ news.image_url }}"  alt="{{ news.title }}">
			<div class="carousel-caption d-none d-md-block">
				<h5>{{ news.title }}</h5>
			</div>
		</div>
		{% endfor %}
		</div>
		<a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
			<span class="carousel-control-prev-icon" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
			<span class="carousel-control-next-icon" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>
</div>

<div class="container">
	{% for news in all_news %}
	<div class="row">
		<div class="col-8">
			<div class="media" style="padding: 3%;">
				<img class="align-self-start mr-3" src="{{ news.image_url }}" width="120" height="120" alt="Generic placeholder image">
				<div class="media-body">
					<h5 class="mt-0">{{ news.title }}</h5>
					<p>{{ news.pub_date }}</p>
					<p class="mb-0">
						{{ news.details|truncatewords:50 }}
					</p>
				</div>
			</div>
		</div>
		<div class="col-4">
			<div class="text-center" style="padding-top: 10%;">
				<a href="{% url 'news:detail' news_site=news.site %}" role="button" class="btn btn-secondary btn-lg">See Details</a>
			</div>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock %}