about/urls.py
from django.conf.urls import url
from . import views

app_name = 'about'

urlpatterns = [
	url(r'about/$', views.testimonial_func, name='about'),
	url(r'create-post/$', views.create_post ,name='create-post'),
]

events/urls.py
from django.urls import path
from . import views

app_name = 'events'
urlpatterns = [
    path('', views.events, name='events'),
    path('register/', views.register, name='register'),
    path('register/member/<str:event_site>/', views.member_regist_event, name='member_register'),
    path('register/google-member/<str:event_site>/', views.google_member_regist_event, name='google_member_register'),
    path('register/non-member/<str:event_site>/', views.non_member_regist_event, name='non_member_register'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.loginpage, name='loginpage'),
]

member/urls.py
from django.urls import path
from . import views

app_name = 'member'
urlpatterns = [
    path('', views.member, name='member'),
    path('success/', views.success, name='success')
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('', views.news, name='news'),
    path('<str:news_site>/', views.detail, name='detail'),
]

student_union/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views
from django.conf import settings

urlpatterns = [
    path('', include('main.urls')),
	path('', include('about.urls')),
    path('events/', include('events.urls')),
    path('news/', include('news.urls')),
    path('member/', include('member.urls')),
    path('userpage/',include('userinfo.urls')),
    path('admin/', admin.site.urls),
    path('login/', views.LoginView.as_view(template_name="useraccounts/login.html"), name='login'),
    path('logout/', views.LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path('auth/', include('social_django.urls', namespace='social')),  # <- Here

]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

def index(request):
    return render(request, 'main/index.html', {})

def loginpage(request):
	return render(request, 'main/loginpage.html')

main/templates/main/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %} · Student Union</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link href="{% static 'main/css/style.css' %}" rel="stylesheet">
        <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
		<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <link href='https://fonts.googleapis.com/css?family=Basic' rel='stylesheet'>
        <style type="text/css">
            .navbar {
            -webkit-box-shadow: 0 8px 6px -6px #999;
            -moz-box-shadow: 0 8px 6px -6px #999;
            box-shadow: 0 8px 6px -6px #999;
            }
        </style>
        <script src="https://apis.google.com/js/platform.js" async defer></script>
        <meta name="google-signin-client_id" content="931296879747-sfs75j0kabjn1hplvr1lun8qsu9q5a8m.apps.googleusercontent.com">
    </head>
    <body>
        <!--Navbar-->
        <nav class="navbar navbar-expand-lg sticky-top navbar-light bg-white">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" style="padding-left: 2%" href="#">
            <img src="{% static 'main/img/logo1.png' %}" width="70" height="70" alt="">
            </a>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                <div class="container" >
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:index' %}" style="padding-right: 55px"><font size="4" face="Basic" color="Black"><Strong>Home</Strong></font></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'news:news' %}" style="padding-right: 55px"><font size="4" face="Basic" color="Black"><Strong>News</Strong></font></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'events:events' %}" style="padding-right: 55px"><font size="4" face="Basic" color="Black"><Strong>Events</Strong></font></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'member:member' %}" style="padding-right: 55px"><font size="4" face="Basic" color="Black"><Strong>Member</Strong></font></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'events:register' %}" style="padding-right: 55px"><font size="4" face="Basic" color="Black"><Strong>Register</Strong></font></a>
                        </li>
						<li class="nav-item">
                            <a class="nav-link" href="{% url 'about:about' %}" style="padding-right: 55px"><font size="4" face="Basic" color="Black"><Strong>About Us</Strong></font></a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" style="padding-right: 10px" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><font size="4" face="Basic" color="Black"><Strong>{{ user.first_name }}</Strong></font></a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <ul>
                                        <li>
                                            <a href="{% url 'logout' %}"   onclick="signOut()">Sign Out                        
                                            </a>
                                        </li>
                                        <li>
                                            <a href="{% url 'userinfo:userpage' %}"> User Info </a>
                                        </li>

                                    </ul>
                                    
                                </div>
                            </li>
                            <script>
                                function signOut() {
                                    alert("Anda berhasil logout")
                                    var auth2 = gapi.auth2.getAuthInstance();
                                    auth2.disconnect();
                                    auth2.signOut().then(function () {
                                        console.log('User signed out.');  

                                    });
                                }
                                function onLoad() {

                                    gapi.load('auth2', function() {
                                        gapi.auth2.init();
                                    
                                    });
                                           
                                }
                            </script>
                            <script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'main:loginpage' %}" style="padding-right: 55px"><font size="4" face="Basic" color="Black"><Strong>Login</Strong></font></a>
                            </li>
                            
                        {% endif %}
                        
                        
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
        <!--footer-->
        <div style="height: auto; background-color: #121516;">
            <div class="container" style="padding:5%; ">
                <div class="row">
                    <div class="col">   
                    </div>
                    <div class="col-6">
                        <div class="text-center">
                            <img  src="{% static 'main/img/logo1.png' %}" class="img-fluid"  alt="...">
                            <h4 style="font-size:20px; color: white; padding-top: 2%;">© STUDENT UNION | Depok, West Java, Indonesia </h4>
                            <div class="row">
                                <div class="col">
                                    <div class="text-center" style="padding-top:1%">
                                        <h6 style="color: white;">P:  +6281317250077</h6>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="text-center" style="padding-top:1%">
                                        <h6 style="color: white;">E:  studentUnion@gmail.com</h6>
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="text-center" style="padding-top:3%">
                                    <h6 style="color: white;">-Kelompok 11 PPW C-</h6>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col">    
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Home{% endblock %}


{% block content %}

<div class="posisi">
	<img src="{% static 'main/img/homes.jpg' %}" alt="" class="img-fluid" style="width:100%;">
	<div class="text-block"> 
		<h1 style="font-size: 8vw; font-family: Basic;">STUDENT<br>UNION</h1>

	    
	</div>
</div>

{% endblock %}

main/templates/main/loginpage.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" itemscope itemtype="http://schema.org/Article">
<head>
	<title>Login</title>
	<meta charset="utf-8">

	
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

  
	<link rel="stylesheet" type="text/css" href="{% static 'main/css/style2.css' %}">

</head>

<body id="LoginForm">
	<div class="container">
		<div class="login-form">
			<div class="main-div">
    			<div class="panel">
    				<img src="https://cdn4.iconfinder.com/data/icons/new-google-logo-2015/400/new-google-favicon-512.png" alt="..." style="max-width: 25%; height: auto; padding: .25rem;">
   					<h2>Login</h2>
   					<p>Please Login With Gmail</p>
   				</div>
    			<form id="Login" method="POST">
    				

    
        			<a type="button" class="loginBtn loginBtn--google" href="{% url 'social:begin' 'google-oauth2' %}"> Login with Google</a>
        			

    			</form>
    		</div>
			
		</div>
	</div>
	



</body>
</html>